# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.7.3

pipelines:
   branches:
     develop:
     - step:
        name: Deploy to develop
        deployment: develop
        caches: 
          - pip
        script: 
          - echo "Deploying to develop environment"
          - apt-get update
          - apt-get install -y libsdl2-dev
          - pip install --upgrade pip
          - pip install -r requirements.txt
          
          # code analysis
          - echo "Code Metrics"
          # error: radon giving no results.
          # - radon cc -n C -s  scripts\
          # - radon  mi -m -s --min B -j  scripts\
          # - radon  raw -s  scripts\
          # - echo "Unused Scripts"
          # error: vulture errors for some reason
          # - vulture --sort-by-size  scripts\
          
          # documentation
          - echo "Build Documentation"
          - cd docs
          - make html
          - cd ..
          - git add .
          - git commit -m "[skip ci] Updated documentation"
          - git push
        artifacts:
          - docs/**

          

