name: Not Quite Paradise

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    # set up python
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    # install libraries
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # run mypy
    - name: Check typing with mypy
      run: |
        mypy